import_list='''
                _
                _
                f                                          utu                     re
                _                             _*_       _m               ain_     _  *_
            du                                          m                              m
          y_                                            t                           hrea
        d*                                              _                       t
     hre                                               ad                      *                                                                                                          abc*aifc*argparse*array*
   as                                              t*                          a                                                                                                 sync                                 hat *as    ync
   i                                             o*             asyncore*atexit*                                                                                              au                                                      dioo
  p                                       *base6          4*bdb*    bina                                                                                                  sc                                                               ii
 *                                       b                i   se                ct*builti                                                                               n                                                                     s*
bz                                      2*                   c                                                                                                     al                                                                            en                                                                                                                                                                                                                                           da
r                                      *                    cg                                                                                                  i*                                                                                 c
                                     g                      i                                                                                                 tb                                                                                     *
                                chunk                        *                                                                                               c                                                                                         ma
                              th                            *                                                                                             cm                                                                                             d
                          *co                               de                                                                                           *c                                                                                               od
ec                     s*                                    c                                                                                          od                                                                                                  eo
p*                 col                                      l                                                                                          e                                                                                                     ct
    i   ons*coll                                       e                                                                                               ct                                                                                                     i
                                                     on                                                                                                s                                                                                                       .
                                                     a                                                                                                 b                                                                                                      c
                                           *co      l                                                                                                  o                                                                                                      r
                                       s y                                                                                                            s                                                                                                        *
                                        c                                                                                                             o                                                                                                        m
                pileall*c               o                                                                                                             n                                                                                                         c
                u              rrent*     c oncu rr                                                                                                   en                                                                                                        t
                 .                    futur     e                                                                                                      s                                                                                                         *
                 c                          onfig                                                                                                      p                                                                                                         a
                 rs                          e     r                                                                                                   *                                                                                                          c
 ontext           l                         ib      *  cop  y*                                                                                         c                                                                                                          o
p       yr         eg                        *   c        P r   of                                                                                      i                                                                                                          l
          e*        c                         r  y        p t                                                                                            *                                                                                                         c
           sv*         cty                     p e       s   *       cu                                                                                  r                                                                                                         s
            es*c         u                      rses     .   a     sc  ii*                                                                               c                                                                                                         u                                       r       ses.
              pa       ne l                  *cu          rs   es.      t ex                                                                             t                                                                                                         p
              a       d*da  t               et im          e*                                                                                             d                                                                                                        b
              m       *  d  bm                                                                                                                            .d                                                                                                       u
              m       b* d   bm.          gnu*                                                                                                             d                                                                                                       b
              m          .             n  d b                                                                                                               m                                                                                                      *
               d       ec              i  mal                                                                              *d                               i                                                                                                      f
               fl      ib       *  d  is*                                                                                                                   d                                                                                                      i
                 s   tu                                                                                                                                     t                                                                                                      i
                  ls   *                                                                                                                                     d                                                                                                     i
                    s     tu                                                                                                                                  ti                                                                                                     ls
                                                                                                                                                                .                                                                                                      a
                              rc                                                                                                                                 h                                                                                                      i
                              v e                                                                                                                                 _                                                                                                      u
                              t i                                                                                                                                 l  *di                                                                                                 s
tu                             ti                                                                                                                                  ls. b                                                                                                 c
   pp                          co                                                                                                                                   mp i                                                                                                 l
    er                       * d                                                                                                                                       is                                                                                               t
     u  t                                                                                                                                                               i                                                                                              ls
     .cc    omp                                                                                                                                                         i                                                                                              l
 er     *                                                                                                                                                               d                                                                                             i
                                    st                                                                                                                              util                                                                                            s.
                                                                                                                                                                   c                                                                                               md
                                                                                                                                                                   *                                                                                              d
                                                                                                                                                                   i                                                                                            st
                                                                                                                                                                    ut                                                                                          i
                                                                                                                                                                      ls                                                                          .command*di
                                                                                                                                                                       st ut                                                                      ils.comman    d .bdi s
                                                                                                                                                                        t                                                                        *dist  utils.com      m
                                                                                                                                                                         and.b                                                                    d    i st_d   um     b
                                                                                                                                                                             *d                                                                   is  t            ut  i
                                                                                                                                                                               l                                                                   s   .co mmand .bdi  s
                                                                                                                                                                                t                                                                  _ ms i   *dis       t
                                                                                                                                                                                 u                                                                 t   ils.c           o
                                                                                                                                                                                 mm                                                                and. bdis           t
                                                                                                                                                                                  _                                                                pa   ck            a
                                                                                                                                                                                   g                                                                e r*              d
                                                                                                                                                                                    i                                                               st                 u
                                                                                                                                                                                     ti                                                              ls                .
                                                                                                                                                                                       c                                                           omm                 a
                                                                                                                                                                                        nd                                                           .b    di  st_    r
                                                                                                                                                                                          pm                                                        *di        stut   i   ls
                                                                                                                                                                                            .                                                        c  om   ma  n    d    .   bdis
                                                                                                                                                                                            t                                                          _w     ini     n    st        *distuti   ls
                                                                                                                                                                                             .                                                       comma    nd.     b     u i  ld*                                     distutils.command.build_cl
                                                                                                                                                                      ib*dis                 tu                                                     ti   ls.    c     o      m   mand.build                                                               _ext*di
                                                                                                                                                                      stutils .               c                                                          omm a   n    d       .b                      uild_py*di                                                        stu
                                                                                                                                                                                             t                                                  i  ls .       com     ma       nd                                          .build_scripts*dist                              uti
                                                                                                                                                                                            l                                                   s    .co     mma  nd   .       ch                                                                       eck*distutils .co     mm
                                                                                                                                                                                            an                                                 d      .          c lea n        *                                                                                           dis  tu
                                                                                                                                                                                           til                                                 s.co                  mma         n                                                                                              d.con
                                                                                                                                                                                           f                                                            ig*dis    tut  i         l                                                                                                s.co
                                                                                                                                                                                         mm                                                        an               d .i          n                                                                                                   st
                                                                                                                                                                                       al                                                               l* dis       t            u t                                                                                                  ils
                                                                                                                                                                                      .c                                                            omma       nd.i n              s                                                                                                   tall
                                                                                                                                                                                    _d        at                                                    a            *                  di                                                                                                   stu
                                                                                                                                                                                   t          il                                                    s            .   c              om                                                                                                     ma
                                                                                                                                                                                 nd           . i                                                   n           s  t                 a                                                                                                     l l
                                                                                                                                                                              _he             ade                                                   r           s *d                 is                                                                                                     tut
                                                                                                                                                                           il                  s.                                                  co           m m                   an                                                                                                     d.i
                                                                                                                                                                        nst                a   l l_lib                                             *            d i                   st                                                                                                      u t
                                                                                                                                                                    il            s.co      mm  a      nd                                          .            i n                  sta                                                                                                       ll
                                                                                                                                                                _scr             i           p   t        s                                        *            d i                  stu                                                                                                       til
                                                                                                                                                             s.                co             m  m         an                                      d            . r                  e                                                                                                          gi
                                                                                                                                                           s                  t               e  r           *d                                    i            st                    u                                                                                                         ti
                                                                                                                                                      ls.              co mman                 d .s             di                                 s   t*d      is                   t                                                                                                           ut
                                                                                                                                                    il               s.                         c o               re                               *   dis     tut                   il                                                                                                          s.
                                                                                                                                                 cy             gw                              in c                com                            p           ile                   r                                                                                                             *
                                                                                                                                               d            i                                    s t                   uti                         l            s.                  de                                                                                                             bu
                                                                                                                                          g*d             is                                     t u                      ti                       l           s .                 de                                                                                                               p_
                                                                                                                                        ut              il                                        * d                       ist                    u    til    s .                d                                                                                                                  ir
                                                                                                                                    _ut              il                                           * d                           is                 t   util      s               .dis t                                                                                                               *d
                                                                                                                                 is                tu                                             t i                              ls              .  errors*dis t                    ut                                                                                                                i
                                                                                                                              ls.              ex                                                 t e                                 nsi         o   n* di   s  t                     u                                                                                                                til
                                                                                                                            s.               fa                                                    nc                                      y_geto     p t*     dis                  tuti                                                                                                                 ls.
                                                                                                                        fi                le_                                                      u t                                                i      l                 *d i                                                                                                                       stu
                                                                                                                      ti                ls                                                          . fi                          le                 l i st*distuti       ls.lo                                                                                                                             g*
                                                                                                                   di              stut                                                              i  l                     s.                       m svc c              ompi        l                                                                                                                     e
                                                                                                                r*d             is                                                                    t u                til  s.spaw               n*     di stutil                      s                                                                                                                    .s
                                                                                                             ys               co                                                                       n f          ig*                            distu  tils                         .te                                                                                                                      x
                                                                                                          t_              fil                                                                           e *    dist   util  s.unixccompiler            * d ist            utils.uti                                                                                                                              l
                                                                                                        *               di                                                                               stut    ils     .                             v e rsion                                                                                                                                                *d
                                                                                                       o            ct                                                                                           e       st*d   ummy_threading*ema  i    l *              email.charset*ema                                                                                                                     il
                                                                                                       .        co                                                                                                 ntentmanag   er*em               ai   l .e ncoder                      s*                                                                                                                    em
                                                                                                      ai     l.                                                                                                                                errors  * e mai                            l.g                                                                                                                    e
                                                                                                      n    e                                                                                                                     rator*               em a i l               .heade                                                                                                                               r
                                                                                                     *     e                                                                                                        mail.h                           eader r egis                                                                                                                                                 t ry
                                                                                                     *    em                                                                                                        ail              .iterators*em a il.m  e                 s sa      ge*  e                                                                                                                           ma
                                                                                                    i    l                                                                                                             .mime*                        e ma  il .parser*emai                  l                                                                                                                              .p
                                                                                                    o   l                                                                                                                                   icy*email.uti  l s                               *                                                                                                                               enc
                                                                                                   od   i                                                                                                                          ngs*                enc odi                   ngs.idna*e                                                                                                                                    nco
                                                                                                   d    i                                                                                                                 ng                         s. m  b c    s*encoding s                                                                                                                                                    .u
                                                                                                   t   f                                                                                                                 _8                _sig*ens  u re  p                                ip*                                                                                                                                    enu
                                                                                                   m   *                                                                                                                  errno*fau                  lth a n      dl er*fcntl*filecmp*      f il                                                                                                                                    einp
                                                                                                   u   t                                                                                                                                        *fnmatch*f pect                               l *                                                                                                                                     f ra
                                                                                                   c   t                                                                                                                             ions*f           tpl   i                       b*funct   oo                                                                                                                                       ls*g
                                                                                                   c    *                                                                                                                     get                     o p    t      *getpass*get                                                                                                                                                          tex
                                                                                                   t    *                                                                                                                    g                   lob* grp     *g                                                                                                                                                                           z i
                                                                                                  p*   h                                                                                                                      ashlib*heapq*          h ma                   c        *html*html.  e                                                                                                                                           nt
                                                                                                  i    t                                                                                                                                            i  es    *html.pa                           r s                                                                                                                                            er
                                                                                                  *    h                                                                                                                                    ttp*    htt p   .                            client*http                                                                                                                                            .co
                                                                                                 o     k                                                                                                                         iejar*h              t t   p               .cookies*  ht      tp                                                                                                                                                  .
                                                                                                 s     e                                                                                                                        rv                   e  r   *imaplib*img                                                                                                                                                                            h
                                                                                                 d     r                                                                                                                         *i  mpo rtlib*impo     r                             t   lib.abc  *                                                                                                                                                 i
                                                                                                 m     p                                                                                                                          or                 tlib       .machinery*impor                   tli                                                                                                                                              b.u
                                                                                                 t    i                                                                                                                                     l   *in sp ec    t                                   *io*                                                                                                                                                ip
                                                                                                 a    d                                                                                                                               d  ress         * i   t                  ertools*json   *                                                                                                                                                       js
                                                                                                 o    n                                                                                                                             .                 t o   o    l*keyword                                                                                                                                                                            *
                                                                                                 l    i                                                                                                                              b          2to3*li n  eca                                  ch   e*                                                                                                                                              lo
                                                                                                 c    a                                                                                                                               le*loggi  n    g*lo  gg          i           ng.conf      ig  *l og                                                                                                                                            gi
                                                                                                 n    g                                                                                                                                             .hand  l er                                 s*lzma *                                                                                                                                             ma
                                                                                                 c    p                                                                                                                                  ath*mailbo  x*ma   i                    lcap*marsha   l*m   at                                                                                                                                             h*
                                                                                                 m    i                                                                                                                                m e            t y   pe       s*mmap                                                                                                                                                                         *m
                                                                                                 o    d                                                                                                                                 ul            efi   nder                                                                                                                                                                                    *
                                                                                                 m    s                                                                                                                                  ilib*msv  c rt*m  u                                ltiproce    ss                                                                                                                                          i
                                                                                                 n    g                                                                                                                                              *m u  ltiprocessing.connect                      i  o                                                                                                                                          n*
                                                                                                 m    ul                                                                                                                                          tiproce   s                               sing.du   mm                                                                                                                                             y
                                                                                                  *    m                                                                                                                                   ul        tipr   o        ce        ssing       .                                                                                                                                                          m
                                                                                                  a    n                                                                                                                                   a         gers   *multip
                                                                                                  r    o                                                                                                                                    cessing.po ol  *m                        ultiproc         e                                                                                                                                                 s
                                                                                                  s    i                                                                                                                                             n g.shar                 edctypes*netrc       *nis*nntpl                                                                                                                                           i
                                                                                                   b   *                                                                                                                                            nu mb    ers*                        o  perat or    *op t p                                                                                                                                          a
                                                                                                   r   s                                                                                                                                      e*os*  os. p  a         th*ossa      udi  odev*pathl        ib                                                                                                                                             *
                                                                                                   p  db*                                                                                                                                     p     ickle  *    pick  let                                                                                                                                                                                 o
                                                                                                    o l                                                                                                                                       s*pipe s *p   kg u                                   til*                                                                                                                                                   pl
                                                                                                    a t                                                                                                                                              fo     r            m*plistli                            b                                                                                                                                            *
                                                                                                    p o                                                                                                                                              plib     *posix*pprint*              p                rof                                                                                                                                             i
                                                                                                    l e                                                                                                                                           *pst at  s*     p  t    y*pwd*py_compile*pyclbr*py                                                                                                                                                       d
                                                                                                    o c                                                                                                                                          *         q     ue     ue*q                                                                                                                                                                               u
                                                                                                   op  r                                                                                                                                          i       *rando                                       m*re*r   ea                                                                                                                                          d
                                                                                                    l  i                                                                                                                                           ne     *r                   ep    rlib*reso   urce*rl        co                                                                                                                                          m
                                                                                                   p   l                                                                                                                                               e  ter          *runpy            *         sched*secre                                                                                                                                              ts
                                                                                                   *    s                                                                                                                                              e  lect*                   selectors*s                                                                                                                                                               he
                                                                                                  lv    e                                                                                                                                              *  shl       ex*shut   il                                                                                                                                                                             *
                                                                                                  s   i gn                                                                                                                                             a  l*site*                                        smtpd*smtp                                                                                                                                          l
                                                                                                  i  b*  s                                                                                                                                             n  dh                                dr*so      cket*so  cketse                                                                                                                                       r
                                                                                                  v  er *s                                                                                                                                             p  wd         *sq     lite3                    *ssl*  stat                                                                                                                                            *
                                                                                                 s   ta t                                                                                                                                              i  st ics*strin              g*str  ing     pr                                                                                                                                                        e
                                                                                                 p  *  st                                                                                                                                              r  uct        *s      u   bpr                                                                                                                                                                         o
                                                                                                ce  s s*                                                                                                                                               su nau  *symt                                  able*sys*     syscon                                                                                     fi                                           g
                                                                                                *s  ysl                                                                                                                                                o  g *t                        abnanny*t       arf    i   le*tel                                                                                  ne         tlib                                   *
                                                                                                 t   e                                                                                                                                                 m                 pfile *te   rm ios*            t     est*                                                                                   tes                 t.s                              up
                                                                                                p    o                                                                                                                                                 r      t *t extw rap*t   hreading   *time*                                                                                                 tim                       ei                            t
                                                                                                *   t                                                            kint                                                                                  e    r*t      kinter   .scro                                    ll                                                                       ed                            te                         x
                                                                                                 t* t                                                             k  i                                                                                       n ter. tix                                 *tkint      er.tt                                                                      k                                *                        t
                                                                                                  o k                                                           en   *                                                                                         t                       o  keniz e*trac e*        tr a                                                                         c                                  eb                     a
                                                                                                 ck*t                                                           ra    c                                                                                                   e      malloc*         tty*turtle*tu                                                                               r                                    tl                    e
                                                                                               demo                                                             *     t                                                                                         ypes*typin              g*unic  oded                                                                                  at a*  u                                      ni                  t
                                                                                             te s                                                               t     *                                                                                       un              ittest.m oc                                                                                            k    * ur                                        l                li
                                                                                           b*ur                                                                 l     l                                                                                       i    b.er    ror                        *urll         ib                                                              .     p a               r                          s               e
                                                                                          *u                                                                    rl     l                                                                                                                 ib.r  equest*urllib.respons                                                                e     *u              rlli                          b              .
                                                                                         ro                                                                      b     o                                                                                                    t  parser* u               u*uuid                                                                       *v    en           v*w ar                           n             in
                                                                                         g                                                                       s     *                                                                                           wave*w   e                   akref*                                                                               we    b          b  ro                              w            ser
                                                                                         *                                                                        w     i                                                                                       nr                 eg*winsound*                wsgiref*w                                                                   s         g  i                                r             ef
                                                                                         .                                                                        h     a                                                                                      n   dle        rs*                      wsgir         ef                                                                    .        h ea                                  d            er
                                                                                        s                                                                         *     w                                                                                                                    sgiref              .si                                                                        m                                             p             le
                                                                                        _                                                                         s     e                                                                                                           rv  e       r*w       sgir  ef                                                                           .ut                                          i             l*
                                                                                        ws gir e f.                                                             val      i                                                                                         d ate *xd  rli      b *xml*xml.dom*                  xml.                                                                  d                                          o                m
                                                                                         .m    in                                                               i        d                                                                                        o   m*xm l.dom      .p                         ulld  om                                                                   *x                                           m               l.
                                                                                           e  tr                                                                e        e                                                                                         .                                 ElementT       re                                                                    e*                                             x               m
                                                                                           l  .                                                                  p       a                                                                                                                  rsers.e xpat*xm    l.p                                                                       a                                               r            sers
                                                                                            .e                                                                     x     p                                                                                                       at.er         ro    rs*xml.                                                                           pa                                                r            se
                                                                                             rs                                                                     .e   x                                                                                          pa       t.model*xml.sax*x                               ml.                                                      s                                                    ax.       ha
                                                                                              ndl                                                                     e  r                                                                                          *xml.sax.                                                 s ax                                                    ut                                                i l
'''
import_list=import_list.replace(' ','').replace('\n','').split('*')
for module in import_list:
	try:
		exec('import '+module)
	except:
		pass
print("Yeah")
